### ISSUE TITLE
wallet corrupted,cant withdraw funds because someone hacked me and tried to steal

### ISSUE THREAD

**Issue by Bojan311** [pooler/electrum-ltc#330] opened 2024-10-21 02:47 UTC

**Comment by pooler** [comment] 2024-10-21 12:32
Duplicate of #332

**Closed as completed by pooler** 2024-10-21 12:32 UTC

**Comment by Bojan311** [comment] 2024-10-21 12:34
But this is not completed,i cant solve this problem bruhhhh

pon, 21. okt 2024. 14:33 pooler ***@***.***> je napisao/la:

**Comment by pooler** [comment] 2024-10-21 12:46
> But this is not completed,i cant solve this problem bruhhhh

If this is the same problem as #332, please use that thread. Otherwise, you should clarify why this is a separate issue.

**Comment by Bojan311** [comment] 2024-10-21 12:59
I still wait for support to send me funds she told me she can send i dont
know why dont sending

pon, 21. okt 2024. 14:46 pooler ***@***.***> je napisao/la:

**Comment by pooler** [comment] 2024-10-21 13:07
> I still wait for support to send me funds she told me she can send i dont know why dont sending

There is no "support". Do not trust anyone posing as official support for Electrum-LTC, they will try to scam you.

**Comment by Bojan311** [comment] 2024-10-21 13:09
Where to contact then?

pon, 21. okt 2024. 15:07 pooler ***@***.***> je napisao/la:

**Comment by pooler** [comment] 2024-10-21 13:21
> Where to contact then?

There is no one to contact. I try to help when I can (see other thread), but Electrum-LTC is free software, it comes with no guarantees and no dedicated support.

**Comment by Bojan311** [comment] 2024-10-21 13:24
Can i contact you somewhere and give u details to try to solve the
problem,i will give you 20% of funds.

pon, 21. okt 2024. 15:21 pooler ***@***.***> je napisao/la:

**Comment by pooler** [comment] 2024-10-21 13:54
> Can i contact you somewhere and give u details to try to solve the problem,i will give you 20% of funds.

No, sorry.
