### ISSUE TITLE
litecoin: (open in wallet) links are broken on macOS

### ISSUE THREAD

**Issue by kosinusbch** [pooler/electrum-ltc#282] opened 2021-11-17 06:15 UTC
Work fine in the Electron Cash, Electrum and Feather wallets, but in Electrum-LTC it gives:

"Error parsing URI:
expected string, not PyQt5.QtCore.QByteArray(b'litecoin:LcUP7ZU3Xpk1BUR3qut3dTjC3aK5JoZMYx?amount=1&message=donation')"

2020 M1 MacBook Pro, macOS 11.4

To replicate:
1. Click on any litecoin: uri (https://electrum-ltc.org/litecoin_URIs.html for example)
2. This happens:

<img width="1095" alt="Screen Shot 2021-11-17 at 10 10 52 AM" src="https://user-images.githubusercontent.com/7502322/142144715-1c1488b0-17ec-46f5-beee-2fb24e7b8937.png">

**Comment by pooler** [comment] 2021-11-17 09:25
Duplicate of #272.

**Closed by pooler** 2021-11-17 09:25 UTC
