### ISSUE TITLE
App close when trying to create hardware wallet

### ISSUE THREAD

**Issue by martinschultzkristensen** [pooler/electrum-ltc#47] opened 2017-05-16 14:02 UTC
Hello electrum team.
My app close when I try to create hardware wallet for my Trezor.
I already have a default wallet. I am on a mac.
What can I do? -Reinstall, or are there other options?

Thanks for a great app.
Regards
Martin

**Comment by pooler** [comment] 2017-05-16 14:07
What version of Electrum-LTC are you using?

**Comment by martinschultzkristensen** [comment] 2017-05-16 15:01
version 2.6.4.2

**Comment by pooler** [comment] 2017-05-16 15:06
Could you please test beta version 2.8.3.2? You can download it from the official site, https://electrum-ltc.org.

**Comment by martinschultzkristensen** [comment] 2017-05-16 15:31
I will. Thanks.

**Comment by martinschultzkristensen** [comment] 2017-05-17 09:17
Hello again.
Unfortunately the beta version 2.8.3.2 doesn't even let me open the program. (It opens and closes immediately)

**Comment by pooler** [comment] 2017-05-17 09:29
What version of macOS are you on?
Also, could you please check whether [Electrum 2.8.2](https://electrum.org/#download) (for Bitcoin) works with Trezor on your computer?

**Comment by martinschultzkristensen** [comment] 2017-05-17 10:30
I'm running Sierra 10.12.4
My Trezor is working with Electrum 2.8.2 (for Bitcoin).

**Comment by pooler** [comment] 2017-05-17 11:46
OK, thank you.
I'm now closing this ticket as it's a duplicate of #43. Please subscribe to it to receive further updates.

**Closed by pooler** 2017-05-17 11:46 UTC
