### ISSUE TITLE
getprivatekeys() takes at least 2 arguments (2 given)

### ISSUE THREAD

**Issue by Volvigo** [pooler/electrum-ltc#105] opened 2017-12-20 06:53 UTC
I am trying to sweep the private keys of my wallet and when i attempt to get them thru the console it returns a bunch of stuff then "getprivatekeys() takes at least 2 arguments (2 given)" I am also getting the error "object of Nonetype has len()"

**Comment by pooler** [comment] 2017-12-20 10:18
Care to share the "bunch of stuff" (which I suppose is a stack trace)?
What version of Electrum-LTC is this, on what OS, and how was it installed/run?

**Comment by Volvigo** [comment] 2017-12-21 06:06
I am on Electrum-LTC version 2.9.3.1 and I run on windows 10
Here's what I meant by a bunch of stuff
getprivatekeys()
Traceback (most recent call last):
  File "C:\Users\milto\AppData\Local\Temp\_MEI172722\gui\qt\main_window.py", line 1715, in <lambda>
    return lambda *args: f(method, args, self.password_dialog)
  File "C:\Users\milto\AppData\Local\Temp\_MEI172722\lib\commands.py", line 111, in _run
    result = f(*args, **{'password':password})
  File "C:\Users\milto\AppData\Local\Temp\_MEI172722\lib\commands.py", line 86, in func_wrapper
    return func(*args, **kwargs)
TypeError: getprivatekeys() takes at least 2 arguments (2 given)

**Comment by pooler** [comment] 2017-12-21 09:07
You must pass `getprivatekeys` an address or a list of addresses. If you want to obtain the private keys of all your non-empty addresses, use:
```
getprivatekeys( map(lambda x: x.get('address'), listunspent()) )
```

**Comment by Volvigo** [comment] 2017-12-22 00:36
Whenever I enter getprivatekeys('address') it returns

getprivatekeys('address')
Traceback (most recent call last):
NameError: name 'address' is not defined

Whenever I enter getprivatekeys( map(lambda x: x.get('address'), listunspent()) ) it returns

getprivatekeys( map(lambda x: x.get('address'), listunspent()) )
Traceback (most recent call last):
  File "<string>", line 1, in <lambda>
NameError: global name 'address' is not defined

**Comment by pooler** [comment] 2017-12-28 18:26
I tried with Electrum-LTC 2.9.3.1 on Windows 10 but I can't reproduce the above. I get your error if I type `getprivatekeys(address)` literally, but if I use an actual address within quotes it works just fine.

**Comment by Volvigo** [comment] 2017-12-28 19:27
I think my wallet just may be corrupted

**Comment by pooler** [comment] 2018-01-09 17:14
Closing because version 2.9.3.1 is no longer supported.

**Closed by pooler** 2018-01-09 17:14 UTC
