### ISSUE TITLE
Ledger devices not recognized 

### ISSUE THREAD

**Issue by TamtamHero** [pooler/electrum-ltc#256] opened 2021-01-27 10:52 UTC
The release provided on the website doesn't recognize ledger devices anymore, as the Litecoin app has been updated and declares a new USB PID.
Could you please update this very old release and put a recent one like 4.0.9.1 instead ?
Thanks :pray:

**Comment by pooler** [comment] 2021-01-27 13:04
Duplicate of #246. The Litecoin Foundation has been working on new official binaries.

**Closed by pooler** 2021-01-27 13:04 UTC

**Comment by TamtamHero** [comment] 2021-01-27 14:05
Any link to follow the progress on this ?

**Comment by pooler** [comment] 2021-01-27 14:19
> Any link to follow the progress on this ? Any ETA ?

No, but it shouldn't take long.

> Are the binaries going to be available on https://electrum-ltc.org/ ?

Yes.

**Comment by ozanyurt** [comment] 2021-02-09 00:18
Any progress on this?

Thanks
