### ISSUE TITLE
Accidently Sent LTC to BTC electrum wallet. 

### ISSUE THREAD

**Issue by joeamelendez** [pooler/electrum-ltc#68] opened 2017-09-08 23:10 UTC
So yeah. I accidentally sent an ltc from my litecoin core wallet to an electrum btc wallet by mistake. It shows that it went through, but there is nothing in my electrum wallet (not that I expected to see an amount) but no message at all. Any suggestions?

**Comment by pooler** [comment] 2017-09-09 07:16
Did you send the coins to a legacy P2SH address starting with `3`?

**Comment by joeamelendez** [comment] 2017-09-09 13:40
Seems that I did use a P2SH Address starting with 3:
https://live.blockcypher.com/ltc/tx/65e21845ea683d1a791e1ae35ea54cb97268a90c2e09b20368a4c5dcfee935a9/

And I used Electrum-LTC after the fact to try and use my seed from the Electrum BTC wallet, but nothing showed up.

**Comment by pooler** [comment] 2017-09-09 14:38
After you load your Electrum seed in Electrum-LTC, do the addresses in the Addresses tab match those generated by Electrum?

You can use [this tool](https://litecoin-project.github.io/p2sh-convert/) to convert between old and new P2SH addresses.

**Comment by joeamelendez** [comment] 2017-09-09 16:54
They do not match.

**Comment by pooler** [comment] 2017-09-09 17:14
Then you probably did something wrong when you tried to restore from seed. Could you please describe the procedure you followed step by step?

**Comment by joeamelendez** [comment] 2017-09-10 15:15
So very likely I did do something wrong in restoring so since I've tried a few different ways:

1) Tried importing a backup wallet from electrum to electrum-ltc... which I never got past the entering password screen.

2) Creating a standard wallet, entering seed (gives msg: Seed Type 2fa), just click next and it stays on a "please wait" screen forever.

3) Creating a standard wallet, entering seed (gives msg: Seed Type 2fa), just choose BIP39 seed, hit next, asks for wallet derivation, click next, don't choose to encrypt wallet and get addresses starting with L

4) Creating a standard wallet, entering seed (gives msg: Seed Type 2fa), just choose BIP39 seed, hit next, asks for wallet derivation, click next, choose to encrypt wallet and get addresses starting with L

5) Create multi-sig wallet, enter seed, can't click next unless I pick bip39, click next, enter derivation , enter cosigner key, (I don't have the private master key, so I enter public cosigner key from electrum (btc) wallet, don't encrypt wallet, get addresses that don't match.

6)Create multi-sig wallet, enter seed, can't click next unless I pick bip39, click next, enter derivation , enter cosigner key, (I don't have the private master key, so I enter public cosigner key from electrum (btc) wallet, don't encrypt wallet, get addresses that don't match.

6)Create multi-sig wallet, enter seed, can't click next unless I pick bip39, click next, enter derivation , enter cosigner key, (I don't have the private master key, so I enter public cosigner key from electrum (btc) wallet, encrypt wallet, get addresses that don't match.

And that's where I currently am.

**Comment by pooler** [comment] 2017-09-10 16:12
Do you remember how you created the original wallet in Electrum? (You said it's a P2SH address, so I suppose it's multi-sig? In that case, wouldn't you have more than one seed?)

What's the difference between 5 and 6 above?

In 5, 6, and 7 I suppose you're getting addresses starting with 'M'. When you say that the addresses don't match, have you first converted them to legacy addresses starting with '3' using the tool I linked above?

**Comment by joeamelendez** [comment] 2017-09-10 16:31
in 6, i should have changed it to encrypt wallet. yes the address start with M, and using the conversion tool they don't match with the addresses in the electrum btc wallet. and I didn't choose multisig but wallet with two-factor authorization when creating the electrum btc wallet. This isn't an option in electrum-ltc when creating a wallet.

**Comment by pooler** [comment] 2017-09-10 17:40
You should have mentioned this earlier. Two-factor authentication is a service provided by TrustedCoin (see [here](http://docs.electrum.org/en/latest/2fa.html)), and they do not support Litecoin, which is why this option isn't present in Electrum-LTC.

Now, the problem is that 2FA seeds are a special variety that isn't supported by Electrum-LTC (for the reason above). It should still be possible to recover the coins, I'm just not entirely sure how without writing ad-hoc code. Here is what I would try. First of all, in Electrum for Bitcoin, make a new wallet restoring from your 2FA seed, and when asked select to disable TrustedCoin. Do not enter a password. Then, close Electrum and open the wallet file you just created in a text editor. You will find 3 xpub and 2 xprv addresses. Open Electrum-LTC and create a new multi-sig wallet with a 2-of-3 scheme. Use the first xprv address and the other two xpub addresses. This should give you a wallet with the right addresses (use the converter to check). Finally, make a wallet for the second signer using the second xprv and the other two xpub addresses.

**Comment by joeamelendez** [comment] 2017-09-10 18:22
I'm sorry, new to this. And by the way, really appreciate your time and information. I followed those steps and was able to require the amounts to the 2 different wallets. I

**Comment by pooler** [comment] 2017-09-10 19:50
@joeamelendez, is the problem resolved then? If so, please close the issue.

**Closed** 2017-09-10 20:07 UTC

**Comment by RAdson7** [comment] 2018-02-07 16:56
Just did it what you recommended wit coment and pooler you save my day. Thank you
