### ISSUE TITLE
Endless sync

### ISSUE THREAD

**Issue by Rafhuseynov** [pooler/electrum-ltc#297] opened 2022-07-25 11:38 UTC
Electrum wallet LTC, open the wallet, enter the password, the wallet opens and starts synchronizing it. Writes 668 blocks, synchronizes up to 667 blocks and starts again from 0 synchronization and so on endlessly, changed the server, set it manually different, does not help. I took the seed phrase, tried to restore it, everything is still the same. Estanovil electrum, restored through the seed, all the same. I deleted electrum completely, deleted the directory, reinstalled electrum, added a file with a wallet to the wallet directory, opened it and everything is still the same, synchronization is constant.

**Comment by pooler** [comment] 2022-07-25 11:48
Duplicate of #298.

**Closed by pooler** 2022-07-25 11:48 UTC
