### ISSUE TITLE
Additional packages in AppImage

### ISSUE THREAD

**Issue by margre8** [pooler/electrum-ltc#232] opened 2020-01-10 06:08 UTC
Greetings,

I tried to build AppImage Electrum-ltc 3.3.8.1 but I'm unable to reproduce Appimage

## Release hash:
`deaa3d17bef124efbf5da4d49eab9272eacb5633e7bd02bd394d47e2991d92a4`

## My build
`cc4c6644cfebcbf4ce5166b921e51ddf246d51db37f9d518405f9cb7770080dc`

After unpack AppImage I see only in release AppImage some additional .py files:

> /usr/lib/python3.6/site-packages/electrum_ltc/gui/qt: icons_rc.py
> /usr/lib/python3.6/site-packages/electrum_ltc/plugins/trezor: client.py
> /usr/lib/python3.6/site-packages/electrum_ltc/plugins/trezor: transport.py
> /usr/lib/python3.6/site-packages/electrum_ltc: plugins.py
> /usr/lib/python3.6/site-packages/: electrum_ltc_gui
> /usr/lib/python3.6/site-packages/: electrum_ltc_plugins

How can I build AppImage correctly? 

Thank you for help

**Comment by pooler** [comment] 2020-01-10 12:44
Duplicate of #230

**Closed by pooler** 2020-01-10 12:44 UTC
