### ISSUE TITLE
Error while sending transaction: 'Bad bech32 checksum'

### ISSUE THREAD

**Issue by kazzkiq** [pooler/electrum-ltc#266] opened 2021-03-22 12:56 UTC
I'm using Electrum-LTC version 4.0.9.2 and just tried to send some LTC to another address, but received this message (I've never before):

![Screenshot from 2021-03-22 09-55-20](https://user-images.githubusercontent.com/1953194/111993007-df6c4480-8af4-11eb-9845-88af3471ecd0.png)

```
Failed to parse 'Pay to' line:
LNgaYKJ5EVVa1GAU24phDRDbEaEBN7cfby...

LnDecodeException(ValueError('Bad bech32 checksum'))
```

Not sure how to proceed. The address seems ok to me. Any ideas how to proceed?

**Comment by pooler** [comment] 2021-03-22 13:39
Duplicate of #265.

**Closed by pooler** 2021-03-22 13:39 UTC
