### ISSUE TITLE
i want to withdraw my funds from ltc wallet

### ISSUE THREAD

**Issue by Bojan311** [pooler/electrum-ltc#331] opened 2024-10-21 02:48 UTC
someone tried to use my wallet,i want funds out,i cant broadcast transactions because wallet is corrupted,help please i have my life savings on it

**Comment by Julietnacy** [comment] 2024-10-21 11:44
@Bojan311 Are you able to sort it out already?

**Comment by pooler** [comment] 2024-10-21 12:32
Duplicate of #332.

**Closed as not planned by pooler** 2024-10-21 12:32 UTC
